/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_me_patch"];
        trace?: never;
    };
    "/muscle-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Muscle Groups */
        get: operations["list_muscle_groups_muscle_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Exercise */
        patch: operations["update_exercise_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/exercises/{exercise_id}/last-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Last Session */
        get: operations["get_last_session_exercises__exercise_id__last_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_exercises__exercise_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prs */
        get: operations["get_prs_exercises__exercise_id__prs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise Progress */
        get: operations["get_exercise_progress_exercises__exercise_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workouts */
        get: operations["list_workouts_workouts_get"];
        put?: never;
        /** Create Workout */
        post: operations["create_workout_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout */
        get: operations["get_workout_workouts__workout_id__get"];
        put?: never;
        post?: never;
        /** Delete Workout */
        delete: operations["delete_workout_workouts__workout_id__delete"];
        options?: never;
        head?: never;
        /** Update Workout */
        patch: operations["update_workout_workouts__workout_id__patch"];
        trace?: never;
    };
    "/workouts/{workout_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Workout */
        post: operations["finish_workout_workouts__workout_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/{workout_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Workout Exercise */
        post: operations["add_workout_exercise_workouts__workout_id__exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-exercises/{workout_exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Workout Exercise */
        delete: operations["delete_workout_exercise_workout_exercises__workout_exercise_id__delete"];
        options?: never;
        head?: never;
        /** Update Workout Exercise */
        patch: operations["update_workout_exercise_workout_exercises__workout_exercise_id__patch"];
        trace?: never;
    };
    "/workout-exercises/{workout_exercise_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Set */
        post: operations["add_set_workout_exercises__workout_exercise_id__sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-exercises/{workout_exercise_id}/sets/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Replace Sets */
        post: operations["bulk_replace_sets_workout_exercises__workout_exercise_id__sets_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Set */
        delete: operations["delete_set_sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Update Set */
        patch: operations["update_set_sets__set_id__patch"];
        trace?: never;
    };
    "/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_analytics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/muscle-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Muscle Group Volume */
        get: operations["get_muscle_group_volume_analytics_muscle_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Volume */
        get: operations["get_volume_analytics_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/plateaus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plateaus */
        get: operations["get_plateaus_analytics_plateaus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DashboardOut */
        DashboardOut: {
            /** Recent Workouts */
            recent_workouts: components["schemas"]["WorkoutSummaryOut"][];
            /** Top Improving Exercises */
            top_improving_exercises: components["schemas"]["TopImprovingExerciseOut"][];
            /** Recent Prs */
            recent_prs: components["schemas"]["NewPROut"][];
            weekly_volume: components["schemas"]["WeeklyVolumeOut"];
            /** Workout Count */
            workout_count: number;
            /** Current Streak Weeks */
            current_streak_weeks: number;
            /** Period Days */
            period_days: number;
        };
        /** E1RMPROut */
        E1RMPROut: {
            estimated_1rm: components["schemas"]["LoadValue"];
            load: components["schemas"]["LoadValue"];
            /** Reps */
            reps: number;
            /**
             * Workout Id
             * Format: uuid
             */
            workout_id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
        };
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Muscle Group Id */
            muscle_group_id: number;
            /** Name */
            name: string;
            load_type: components["schemas"]["LoadType"];
            /** @default e1rm */
            progression_metric: components["schemas"]["ProgressionMetric"];
            /**
             * Default Increment G
             * @default 2500
             */
            default_increment_g: number;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Muscle Group Id */
            muscle_group_id: number;
            /** Name */
            name: string;
            load_type: components["schemas"]["LoadType"];
            progression_metric: components["schemas"]["ProgressionMetric"];
            /** Default Increment G */
            default_increment_g: number;
            /** Is Active */
            is_active: boolean;
            /** Is Custom */
            is_custom: boolean;
        };
        /** ExercisePRsOut */
        ExercisePRsOut: {
            weight_pr: components["schemas"]["WeightPROut"] | null;
            rep_pr: components["schemas"]["RepPROut"] | null;
            e1rm_pr: components["schemas"]["E1RMPROut"] | null;
            session_volume_pr: components["schemas"]["SessionVolumePROut"] | null;
        };
        /** ExerciseUpdate */
        ExerciseUpdate: {
            /** Name */
            name?: string | null;
            /** Muscle Group Id */
            muscle_group_id?: number | null;
            load_type?: components["schemas"]["LoadType"] | null;
            progression_metric?: components["schemas"]["ProgressionMetric"] | null;
            /** Default Increment G */
            default_increment_g?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** FinishSummaryOut */
        FinishSummaryOut: {
            /** Exercise Count */
            exercise_count: number;
            /** Total Working Sets */
            total_working_sets: number;
            total_volume: components["schemas"]["LoadValue"];
            /** Duration Minutes */
            duration_minutes: number;
            /** New Prs */
            new_prs: components["schemas"]["NewPROut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryPageOut */
        HistoryPageOut: {
            /** Sessions */
            sessions: components["schemas"]["SessionOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** LastSessionOut */
        LastSessionOut: {
            /** Has Data */
            has_data: boolean;
            session: components["schemas"]["SessionOut"] | null;
            bests: components["schemas"]["ExercisePRsOut"];
        };
        /**
         * LoadType
         * @enum {string}
         */
        LoadType: "barbell_total" | "dumbbell_per_hand" | "machine_total" | "bodyweight" | "bodyweight_added" | "assisted";
        /** LoadValue */
        LoadValue: {
            /** Grams */
            grams: number;
            /** Display */
            display: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MuscleGroupOut */
        MuscleGroupOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Display Order */
            display_order: number;
        };
        /** MuscleGroupVolumeOut */
        MuscleGroupVolumeOut: {
            /** Muscle Group Slug */
            muscle_group_slug: string;
            /** Muscle Group Name */
            muscle_group_name: string;
            volume: components["schemas"]["LoadValue"];
            /** Working Set Count */
            working_set_count: number;
        };
        /** NewPROut */
        NewPROut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /**
             * Pr Type
             * @enum {string}
             */
            pr_type: "weight" | "rep" | "e1rm" | "session_volume";
            value: components["schemas"]["LoadValue"];
            /** Reps */
            reps: number | null;
            /**
             * Workout Id
             * Format: uuid
             */
            workout_id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
        };
        /** PlateauOut */
        PlateauOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /**
             * Metric
             * @enum {string}
             */
            metric: "e1rm" | "top_weight" | "volume" | "reps_at_load";
            /** Session Count */
            session_count: number;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /** Window Days */
            window_days: number;
            /** Weeks Since New Best */
            weeks_since_new_best: number;
            /** Improvement Pct */
            improvement_pct: number;
        };
        /**
         * ProgressionMetric
         * @enum {string}
         */
        ProgressionMetric: "e1rm" | "top_weight" | "volume" | "reps_at_load";
        /** ProgressionOut */
        ProgressionOut: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "e1rm" | "top_weight" | "volume" | "reps_at_load";
            /** Has Data */
            has_data: boolean;
            /** Session Count */
            session_count: number;
            /** Starting Value */
            starting_value?: number | null;
            /** Current Value */
            current_value?: number | null;
            /** Starting Display */
            starting_display?: string | null;
            /** Current Display */
            current_display?: string | null;
            /** Absolute Change */
            absolute_change?: number | null;
            /** Percent Change */
            percent_change?: number | null;
            /** Direction */
            direction?: ("improving" | "flat" | "declining") | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RepPROut */
        RepPROut: {
            /** Reps */
            reps: number;
            load: components["schemas"]["LoadValue"];
            /**
             * Workout Id
             * Format: uuid
             */
            workout_id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Workout Id
             * Format: uuid
             */
            workout_id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
            /** Sets */
            sets: components["schemas"]["SetOut"][];
            volume: components["schemas"]["LoadValue"];
            /** Working Set Count */
            working_set_count: number;
            best_e1rm: components["schemas"]["LoadValue"] | null;
        };
        /** SessionVolumePROut */
        SessionVolumePROut: {
            volume: components["schemas"]["LoadValue"];
            /**
             * Workout Id
             * Format: uuid
             */
            workout_id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
        };
        /** SetIn */
        SetIn: {
            /** Load G */
            load_g: number;
            /** Reps */
            reps: number;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
            /** Rpe */
            rpe?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** SetOut */
        SetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Set Number */
            set_number: number;
            load: components["schemas"]["LoadValue"];
            /** Reps */
            reps: number;
            /** Is Warmup */
            is_warmup: boolean;
            /** Rpe */
            rpe: number | null;
            /** Notes */
            notes: string | null;
        };
        /** SetUpdate */
        SetUpdate: {
            /** Load G */
            load_g?: number | null;
            /** Reps */
            reps?: number | null;
            /** Is Warmup */
            is_warmup?: boolean | null;
            /** Rpe */
            rpe?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TopImprovingExerciseOut */
        TopImprovingExerciseOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /**
             * Metric
             * @enum {string}
             */
            metric: "e1rm" | "top_weight" | "volume" | "reps_at_load";
            /** Percent Change */
            percent_change: number;
        };
        /**
         * UnitPref
         * @enum {string}
         */
        UnitPref: "kg" | "lb";
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            unit_preference: components["schemas"]["UnitPref"];
            /** Bodyweight G */
            bodyweight_g: number | null;
        };
        /** UserUpdate */
        UserUpdate: {
            unit_preference?: components["schemas"]["UnitPref"] | null;
            /** Bodyweight G */
            bodyweight_g?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeByPeriodOut */
        VolumeByPeriodOut: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            volume: components["schemas"]["LoadValue"];
        };
        /** WeeklyVolumeOut */
        WeeklyVolumeOut: {
            current_week: components["schemas"]["LoadValue"];
            previous_week: components["schemas"]["LoadValue"];
            /** Percent Change */
            percent_change: number | null;
        };
        /** WeightPROut */
        WeightPROut: {
            load: components["schemas"]["LoadValue"];
            /** Reps */
            reps: number;
            /**
             * Workout Id
             * Format: uuid
             */
            workout_id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
        };
        /** WorkoutCreate */
        WorkoutCreate: {
            /** Performed On */
            performed_on?: string | null;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutExerciseCreate */
        WorkoutExerciseCreate: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutExerciseOut */
        WorkoutExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            exercise: components["schemas"]["ExerciseOut"];
            /** Position */
            position: number;
            /** Notes */
            notes: string | null;
            /** Sets */
            sets: components["schemas"]["SetOut"][];
        };
        /** WorkoutExerciseUpdate */
        WorkoutExerciseUpdate: {
            /** Position */
            position?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutOut */
        WorkoutOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Title */
            title: string | null;
            /** Notes */
            notes: string | null;
            /** Workout Exercises */
            workout_exercises: components["schemas"]["WorkoutExerciseOut"][];
        };
        /** WorkoutSummaryOut */
        WorkoutSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Title */
            title: string | null;
            /** Exercise Count */
            exercise_count: number;
        };
        /** WorkoutUpdate */
        WorkoutUpdate: {
            /** Performed On */
            performed_on?: string | null;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutsPageOut */
        WorkoutsPageOut: {
            /** Workouts */
            workouts: components["schemas"]["WorkoutSummaryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    patch_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_muscle_groups_muscle_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuscleGroupOut"][];
                };
            };
        };
    };
    list_exercises_exercises_get: {
        parameters: {
            query?: {
                q?: string | null;
                muscle_group?: string | null;
                include_custom?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_last_session_exercises__exercise_id__last_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_exercises__exercise_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prs_exercises__exercise_id__prs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePRsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_progress_exercises__exercise_id__progress_get: {
        parameters: {
            query?: {
                period?: "30d" | "90d" | "1y" | "all";
            };
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workouts_workouts_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutsPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_workouts__workout_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_workouts__workout_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_workouts__workout_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_workout_workouts__workout_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_workout_exercise_workouts__workout_id__exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_exercise_workout_exercises__workout_exercise_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_exercise_workout_exercises__workout_exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_set_workout_exercises__workout_exercise_id__sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_replace_sets_workout_exercises__workout_exercise_id__sets_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_set_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_analytics_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    get_muscle_group_volume_analytics_muscle_groups_get: {
        parameters: {
            query?: {
                period?: "30d" | "90d" | "1y" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuscleGroupVolumeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volume_analytics_volume_get: {
        parameters: {
            query?: {
                period?: "30d" | "90d" | "1y" | "all";
                granularity?: "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeByPeriodOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plateaus_analytics_plateaus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlateauOut"][];
                };
            };
        };
    };
}
